@ASSISTENTE.API_HostAddress = http://localhost:5249

POST {{ASSISTENTE.API_HostAddress}}/api/answer/
Content-Type: application/json
Accept: application/json

{
  "question": "How to configure VPS?"
}

###
