@ApiUrl = http://localhost:1009
@AccessToken = ""

###

POST {{ApiUrl}}/api/questions/
Content-Type: application/json
Accept: application/json

{
  "question": "How to configure VPS?",
  "connectionId": "XD-1234"
}

###

GET {{ApiUrl}}/api/questions/5b6cef00-dfc5-4c9b-958e-04526ae22e6c

###

GET {{ApiUrl}}/api/questions/count

Authorization: Bearer {{AccessToken}}

###

GET {{ApiUrl}}/api/resources/count

###